import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [{type: 'autogenerated', dirName: 'recipes'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
  ],

  // API Reference sidebar - will be populated by TypeDoc
  apiSidebar: [
    {type: 'doc', id: 'api-intro', label: 'API Overview'},
    {type: 'autogenerated', dirName: 'api-reference'}
  ],

};

export default sidebars;
